echo "Logout [$(date '+%a, %d. %b %H:%M')]" >> ~/git.log 
echo -e "\nPushing dot-files..." | tee --append ~/git.log 
cd ~/dot-files
echo
git status
echo

choice=""
read -e -p "Commit and push changes y/n? (default is y) " choice
choice=${choice:-y}

if [[ ${choice} == y ]]
then
	git commit -a -m 'Autogenerated commit on logout'
	git push origin master 2>&1 >> ~/git.log | tee --append ~/git.log
	if [ "$?" != "0" ]; then
		echo -e "\n$RED  Error in git push of dot-files... $NORMAL"
		sleep 5
	fi
fi
cd


echo -e "\nPushing shell scripts..." | tee --append ~/git.log 
cd ~/github/frankMilde/shell-scripts/
echo
git status
echo

read -e -p "Commit and push changes y/n? (default is y) " choice
choice=${choice:-y}

if [[ ${choice} == y ]]
then
	git commit -a -m 'Autogenerated commit on logout'
	git push origin master 2>&1 >> ~/git.log | tee --append ~/git.log
	if [ "$?" != "0" ]; then
		echo -e "\n$RED  Error in git push of shell-scripts... $NORMAL"
		sleep 5
	fi
	cd
fi
