echo -e "\nPushing dot-files..."
cd ~/dot-files
git status

local choice=""
read -e -p "Commit and push changes y/n? (default is y) " choice
choice=${choice:-y}

if [[ ${choice} == y ]]
then
	git commit -a -m 'Autogenerated commit on logout'
	git push origin master
	if [ "$?" != "0" ]; then
		echo -e "\n$RED  Error in git push of dot-files...$NORMAL " 1>&2
		sleep 5
	fi
fi
cd



echo -e "\nPushing shell scripts..."
cd ~/github/shell-scripts/
git status

read -e -p "Commit and push changes y/n? (default is y) " choice
choice=${choice:-y}

if [[ ${choice} == y ]]
then
	git commit -a -m 'Autogenerated commit on logout'
	git push origin master
	if [ "$?" != "0" ]; then
		echo -e "\n$RED  Error in git push of dot-files...$NORMAL " 1>&2
		sleep 5
	fi
	cd
fi
